import { z } from 'zod';

/**
 * Environment validation — INFRASTRUCTURE ONLY.
 *
 * The single most important thing this schema does is what it does NOT
 * validate: no provider API key is required at boot. The previous design
 * validated ANTHROPIC_API_KEY and crashed without it, which was wrong twice
 * over — it hardcoded a vendor into the boot sequence, and it made a fresh
 * deploy unbootable before an admin had ever logged in.
 *
 * Provider credentials arrive through the admin panel and live in the vault.
 * A deployment with nothing configured boots healthy-but-degraded.
 */

const base64Bytes = (bytes: number) =>
  z.string().refine(
    (value) => {
      try {
        return Buffer.from(value, 'base64').length === bytes;
      } catch {
        return false;
      }
    },
    { message: `must be exactly ${bytes} bytes, base64-encoded` },
  );

export const EnvSchema = z
  .object({
    NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),

    // Platform-injected. The Nest starter hardcodes 3000; we read it.
    PORT: z.coerce.number().int().positive().default(3000),

    // Pooled at runtime, unpooled for migrations. Omitting DIRECT_URL is the
    // classic first-deploy failure on Neon.
    DATABASE_URL: z.string().min(1),
    DIRECT_URL: z.string().min(1),

    /**
     * 32 bytes, base64. Losing this means re-entering every provider key —
     * there is no recovery path, by design. Back it up outside the platform.
     */
    MASTER_ENCRYPTION_KEY: base64Bytes(32),

    ADMIN_EMAIL: z.string().email(),
    /**
     * argon2id hash, generated by scripts/hash-password.ts. Plaintext never
     * exists in the repo, the database, or the container.
     *
     * Optional so that a fresh environment can boot and report a degraded
     * admin surface rather than crash — the same philosophy as the provider
     * key. The guard refuses all logins when it is absent.
     */
    ADMIN_PASSWORD_HASH: z.string().startsWith('$argon2id$').optional(),

    SESSION_SECRET: z.string().min(32),

    /** The web origin, exactly. Comma-separated for multiple environments. */
    CORS_ORIGIN: z.string().min(1),

    // ── optional first-boot provider seed (CI and fresh databases only) ──
    AI_BOOTSTRAP_PROVIDER: z.enum(['google', 'anthropic']).optional(),
    AI_BOOTSTRAP_API_KEY: z.string().min(1).optional(),
    AI_BOOTSTRAP_MODEL: z.string().min(1).optional(),

    /** Only meaningful on a provider with explicit caching. Default off. */
    WARM_CACHE_ON_BOOT: z
      .enum(['true', 'false'])
      .default('false')
      .transform((v) => v === 'true'),
  })
  // A partial bootstrap triple is a misconfiguration that would otherwise fail
  // silently on first boot and leave the deployment degraded for no clear
  // reason.
  .refine(
    (env) =>
      [env.AI_BOOTSTRAP_PROVIDER, env.AI_BOOTSTRAP_API_KEY, env.AI_BOOTSTRAP_MODEL].filter(Boolean)
        .length !== 1,
    {
      message:
        'AI_BOOTSTRAP_* must be set together or not at all '
        + '(provider, api key, and model).',
      path: ['AI_BOOTSTRAP_PROVIDER'],
    },
  );

export type Env = z.infer<typeof EnvSchema>;

/**
 * Passed to `ConfigModule.forRoot({ validate })`. Kept as
 * `(config) => Schema.parse(config)` so the zod schema drops straight in.
 */
export function validateEnv(config: Record<string, unknown>): Env {
  const result = EnvSchema.safeParse(config);
  if (!result.success) {
    const detail = result.error.issues
      .map((issue) => `  ${issue.path.join('.') || '(root)'}: ${issue.message}`)
      .join('\n');
    throw new Error(`Invalid environment configuration:\n${detail}`);
  }
  return result.data;
}

export const corsOrigins = (env: Env): string[] =>
  env.CORS_ORIGIN.split(',').map((o) => o.trim()).filter(Boolean);
